--[[
    Level Data for Cave Fall
    Generated by Map Editor Export
    All coordinates in SCREEN SPACE (Y-down), 108x192
]]

local levels = {}

levels[1] = {
    stencilFile = "maps/level_1_stencil.png",
    textureFile = "maps/level_1_texture.png",
    playerStart = {x = 18, y = 78},
    platformXMin = 12,
    platformXMax = 24,
    bats = {
        {x = 90, y = 90},
        {x = 66, y = 90},
    },
    airWalls = {
        {x = 30, y = 78},
        {x = 6, y = 78},
    },
}

levels[2] = {
    stencilFile = "maps/level_2_stencil.png",
    textureFile = "maps/level_2_texture.png",
    playerStart = {x = 30, y = 42},
    platformXMin = 12,
    platformXMax = 36,
    bats = {
        {x = 54, y = 78},
        {x = 78, y = 150},
        {x = 54, y = 126},
    },
    airWalls = {
        {x = 42, y = 42},
        {x = 6, y = 42},
    },
}

levels[3] = {
    stencilFile = "maps/level_3_stencil.png",
    textureFile = "maps/level_3_texture.png",
    playerStart = {x = 42, y = 30},
    platformXMin = 0,
    platformXMax = 107,
    bats = {
        {x = 60, y = 102},
        {x = 24, y = 102},
        {x = 60, y = 48},
        {x = 24, y = 48},
        {x = 60, y = 162},
        {x = 24, y = 162},
    },
    airWalls = {
        {x = 42, y = 30},
    },
}

levels[4] = {
    stencilFile = "maps/level_4_stencil.png",
    textureFile = "maps/level_4_texture.png",
    playerStart = {x = 30, y = 48},
    platformXMin = 12,
    platformXMax = 36,
    bats = {
        {x = 30, y = 114},
        {x = 78, y = 60},
        {x = 72, y = 150},
        {x = 54, y = 132},
    },
    airWalls = {
        {x = 42, y = 48},
        {x = 6, y = 48},
    },
}

levels[5] = {
    stencilFile = "maps/level_5_stencil.png",
    textureFile = "maps/level_5_texture.png",
    playerStart = {x = 18, y = 18},
    platformXMin = 0,
    platformXMax = 36,
    bats = {
        {x = 30, y = 138},
        {x = 54, y = 138},
        {x = 78, y = 138},
    },
    airWalls = {
        {x = 42, y = 18},
    },
}

levels[6] = {
    stencilFile = "maps/level_6_stencil.png",
    textureFile = "maps/level_6_texture.png",
    playerStart = {x = 18, y = 30},
    platformXMin = 0,
    platformXMax = 48,
    bats = {
        {x = 66, y = 90},
        {x = 90, y = 90},
        {x = 18, y = 138},
        {x = 42, y = 150},
        {x = 66, y = 150},
        {x = 90, y = 174},
    },
    airWalls = {
        {x = 54, y = 30},
    },
}

levels[7] = {
    stencilFile = "maps/level_7_stencil.png",
    textureFile = "maps/level_7_texture.png",
    playerStart = {x = 18, y = 30},
    platformXMin = 0,
    platformXMax = 24,
    bats = {
        {x = 42, y = 54},
        {x = 66, y = 54},
        {x = 90, y = 126},
        {x = 54, y = 126},
        {x = 84, y = 168},
        {x = 24, y = 132},
    },
    airWalls = {
        {x = 30, y = 36},
        {x = 30, y = 24},
    },
}

levels[8] = {
    stencilFile = "maps/level_8_stencil.png",
    textureFile = "maps/level_8_texture.png",
    playerStart = {x = 54, y = 42},
    platformXMin = 42,
    platformXMax = 66,
    bats = {
        {x = 90, y = 54},
        {x = 18, y = 78},
        {x = 30, y = 174},
        {x = 78, y = 174},
        {x = 66, y = 42},
    },
}

levels[9] = {
    stencilFile = "maps/level_9_stencil.png",
    textureFile = "maps/level_9_texture.png",
    playerStart = {x = 18, y = 66},
    platformXMin = 0,
    platformXMax = 36,
    bats = {
        {x = 60, y = 78, moveDir = "HORIZONTAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = -1},
        {x = 60, y = 108, moveDir = "HORIZONTAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
        {x = 78, y = 126},
    },
    airWalls = {
        {x = 42, y = 66},
    },
}

levels[10] = {
    stencilFile = "maps/level_10_stencil.png",
    textureFile = "maps/level_10_texture.png",
    playerStart = {x = 42, y = 66},
    platformXMin = 36,
    platformXMax = 48,
    bats = {
        {x = 54, y = 102, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 78, y = 126, moveDir = "VERTICAL", moveDist = 36, moveSpeed = 0.6, moveStartDir = 1},
    },
    airWalls = {
        {x = 54, y = 66},
        {x = 30, y = 66},
    },
}

levels[11] = {
    stencilFile = "maps/level_11_stencil.png",
    textureFile = "maps/level_11_texture.png",
    playerStart = {x = 54, y = 72},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 66, y = 84, moveDir = "VERTICAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 90, y = 84, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3},
        {x = 18, y = 84, moveDir = "VERTICAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 42, y = 84, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
    },
    airWalls = {
        {x = 42, y = 72},
        {x = 66, y = 72},
    },
}

levels[12] = {
    stencilFile = "maps/level_12_stencil.png",
    textureFile = "maps/level_12_texture.png",
    playerStart = {x = 18, y = 66},
    platformXMin = 0,
    platformXMax = 24,
    bats = {
        {x = 18, y = 114, moveDir = "VERTICAL", moveDist = 24, moveSpeed = 0.6, moveStartDir = 1},
        {x = 60, y = 78, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
        {x = 60, y = 156, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 60, y = 180, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
        {x = 48, y = 126},
    },
    airWalls = {
        {x = 30, y = 66},
    },
}

levels[13] = {
    stencilFile = "maps/level_13_stencil.png",
    textureFile = "maps/level_13_texture.png",
    playerStart = {x = 30, y = 42},
    platformXMin = 0,
    platformXMax = 36,
    bats = {
        {x = 84, y = 72, moveDir = "HORIZONTAL", moveDist = 24, moveSpeed = 0.3, moveStartDir = -1},
        {x = 48, y = 72, moveDir = "VERTICAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
        {x = 66, y = 114, moveDir = "HORIZONTAL", moveDist = 24, moveSpeed = 0.6, moveStartDir = -1},
        {x = 78, y = 186},
    },
    airWalls = {
        {x = 42, y = 42},
    },
}

levels[14] = {
    stencilFile = "maps/level_14_stencil.png",
    textureFile = "maps/level_14_texture.png",
    playerStart = {x = 30, y = 90},
    platformXMin = 0,
    platformXMax = 48,
    bats = {
        {x = 60, y = 102},
        {x = 96, y = 102},
    },
    voidBats = {
        {x = 78, y = 126},
        {x = 42, y = 126},
    },
    airWalls = {
        {x = 54, y = 90},
    },
}

levels[15] = {
    stencilFile = "maps/level_15_stencil.png",
    textureFile = "maps/level_15_texture.png",
    playerStart = {x = 30, y = 90},
    platformXMin = 0,
    platformXMax = 48,
    bats = {
        {x = 60, y = 102},
        {x = 96, y = 102, moveDir = "HORIZONTAL", moveDist = 24, moveSpeed = 0.3, moveStartDir = -1},
    },
    voidBats = {
        {x = 78, y = 126, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
        {x = 42, y = 126},
    },
    airWalls = {
        {x = 54, y = 90},
    },
}

levels[16] = {
    stencilFile = "maps/level_16_stencil.png",
    textureFile = "maps/level_16_texture.png",
    playerStart = {x = 6, y = 66},
    platformXMin = 0,
    platformXMax = 12,
    bats = {
        {x = 54, y = 144, moveDir = "VERTICAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 18, y = 126, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
        {x = 90, y = 126, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.6, moveStartDir = 1},
    },
    voidBats = {
        {x = 12, y = 168, moveDir = "HORIZONTAL", moveSpeed = 0.3},
        {x = 36, y = 155, moveDir = "VERTICAL", moveDist = 12, moveSpeed = 0.3},
    },
    airWalls = {
        {x = 18, y = 66},
    },
}

levels[17] = {
    stencilFile = "maps/level_17_stencil.png",
    textureFile = "maps/level_17_texture.png",
    playerStart = {x = 54, y = 66},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 72, y = 90, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
        {x = 84, y = 90, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
        {x = 36, y = 90, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
        {x = 24, y = 90, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
    },
    voidBats = {
        {x = 54, y = 108},
    },
    airWalls = {
        {x = 66, y = 66},
        {x = 42, y = 66},
    },
}

levels[18] = {
    stencilFile = "maps/level_18_stencil.png",
    textureFile = "maps/level_18_texture.png",
    playerStart = {x = 54, y = 54},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 90, y = 78},
        {x = 18, y = 78},
    },
    mirrorLines = {
        {x = 12, y = 132, length = 84},
    },
    airWalls = {
        {x = 66, y = 54},
        {x = 42, y = 54},
    },
}

levels[19] = {
    stencilFile = "maps/level_19_stencil.png",
    textureFile = "maps/level_19_texture.png",
    playerStart = {x = 54, y = 54},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 90, y = 78},
        {x = 54, y = 162},
        {x = 30, y = 102},
    },
    voidBats = {
        {x = 18, y = 42},
    },
    jumpBats = {
        {x = 18, y = 78},
    },
    mirrorLines = {
        {x = 12, y = 132, length = 84},
    },
    airWalls = {
        {x = 66, y = 54},
        {x = 42, y = 54},
    },
    safeZones = {
        {x = 54, y = 186},
        {x = 66, y = 186},
        {x = 42, y = 186},
    },
}

levels[20] = {
    stencilFile = "maps/level_20_stencil.png",
    textureFile = "maps/level_20_texture.png",
    playerStart = {x = 54, y = 54},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 90, y = 78},
        {x = 54, y = 162},
        {x = 30, y = 102},
    },
    voidBats = {
        {x = 18, y = 42},
    },
    jumpBats = {
        {x = 18, y = 78},
    },
    mirrorLines = {
        {x = 12, y = 132, length = 84},
    },
    airWalls = {
        {x = 66, y = 54},
        {x = 42, y = 54},
    },
    safeZones = {
        {x = 54, y = 186},
        {x = 66, y = 186},
        {x = 42, y = 186},
    },
}

levels[21] = {
    stencilFile = "maps/level_21_stencil.png",
    textureFile = "maps/level_21_texture.png",
    playerStart = {x = 18, y = 30},
    platformXMin = 0,
    platformXMax = 24,
    bats = {
        {x = 60, y = 36, moveDir = "HORIZONTAL", moveDist = 24, moveSpeed = 0.3, moveStartDir = 1},
        {x = 84, y = 36, moveDir = "HORIZONTAL", moveDist = 24, moveSpeed = 0.3, moveStartDir = -1},
        {x = 18, y = 156},
        {x = 48, y = 144, moveDir = "HORIZONTAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = -1},
    },
    voidBats = {
        {x = 78, y = 144},
        {x = 60, y = 78},
    },
    mirrorLines = {
        {x = 18, y = 102, length = 56},
    },
    airWalls = {
        {x = 30, y = 30},
    },
    safeZones = {
        {x = 30, y = 6},
        {x = 18, y = 6},
        {x = 6, y = 6},
    },
}

levels[22] = {
    stencilFile = "maps/level_22_stencil.png",
    textureFile = "maps/level_22_texture.png",
    playerStart = {x = 18, y = 30},
    platformXMin = 0,
    platformXMax = 24,
    bats = {
        {x = 96, y = 78},
        {x = 96, y = 114},
        {x = 96, y = 162},
    },
    voidBats = {
        {x = 96, y = 30},
    },
    mirrorLines = {
        {x = 36, y = 168, length = 24},
        {x = 36, y = 96, length = 24},
    },
    airWalls = {
        {x = 30, y = 30},
    },
    safeZones = {
        {x = 42, y = 186},
        {x = 54, y = 186},
    },
}

levels[23] = {
    stencilFile = "maps/level_23_stencil.png",
    textureFile = "maps/level_23_texture.png",
    playerStart = {x = 78, y = 150},
    platformXMin = 72,
    platformXMax = 107,
    bats = {
        {x = 48, y = 150},
        {x = 30, y = 36},
        {x = 60, y = 36},
        {x = 90, y = 150},
        {x = 78, y = 132},
    },
    voidBats = {
        {x = 66, y = 120},
    },
    jumpBats = {
        {x = 18, y = 150},
        {x = 84, y = 36},
    },
    mirrorLines = {
        {x = 12, y = 96, length = 30},
        {x = 78, y = 96, length = 18},
    },
    airWalls = {
        {x = 66, y = 150},
    },
}

levels[24] = {
    stencilFile = "maps/level_24_stencil.png",
    textureFile = "maps/level_24_texture.png",
    playerStart = {x = 18, y = 162},
    platformXMin = 0,
    platformXMax = 24,
    bats = {
        {x = 18, y = 132},
        {x = 42, y = 66},
    },
    voidBats = {
        {x = 30, y = 120},
    },
    jumpBats = {
        {x = 60, y = 168},
        {x = 60, y = 18},
    },
    mirrorLines = {
        {x = 48, y = 120, length = 24},
        {x = 36, y = 48, length = 12},
    },
    airWalls = {
        {x = 30, y = 162},
    },
}

levels[25] = {
    stencilFile = "maps/level_25_stencil.png",
    textureFile = "maps/level_25_texture.png",
    playerStart = {x = 6, y = 66},
    platformXMin = 0,
    platformXMax = 12,
    bats = {
        {x = 90, y = 66},
        {x = 78, y = 54},
        {x = 66, y = 42},
        {x = 54, y = 30},
        {x = 18, y = 150},
        {x = 42, y = 150},
        {x = 66, y = 150},
    },
    voidBats = {
        {x = 89, y = 149},
    },
    mirrorLines = {
        {x = 12, y = 78, length = 12},
        {x = 36, y = 78, length = 12},
        {x = 60, y = 78, length = 12},
        {x = 84, y = 78, length = 12},
        {x = 12, y = 120, length = 12},
    },
    airWalls = {
        {x = 18, y = 66},
    },
    safeZones = {
        {x = 18, y = 186},
        {x = 30, y = 186},
        {x = 42, y = 186},
        {x = 54, y = 186},
        {x = 66, y = 186},
        {x = 78, y = 186},
        {x = 90, y = 186},
    },
}

levels[26] = {
    stencilFile = "maps/level_26_stencil.png",
    textureFile = "maps/level_26_texture.png",
    playerStart = {x = 6, y = 66},
    platformXMin = 0,
    platformXMax = 12,
    bats = {
        {x = 18, y = 102, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 42, y = 48, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
        {x = 66, y = 114, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 90, y = 36, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
    },
    voidBats = {
        {x = 66, y = 126},
        {x = 42, y = 138},
        {x = 18, y = 30},
    },
    mirrorLines = {
        {x = 12, y = 78, length = 12},
        {x = 36, y = 78, length = 12},
        {x = 60, y = 78, length = 12},
        {x = 84, y = 78, length = 12},
    },
    airWalls = {
        {x = 18, y = 66},
    },
    safeZones = {
        {x = 18, y = 186},
        {x = 30, y = 186},
        {x = 42, y = 186},
        {x = 54, y = 186},
        {x = 66, y = 186},
        {x = 78, y = 186},
        {x = 90, y = 186},
    },
}

levels[27] = {
    stencilFile = "maps/level_27_stencil.png",
    textureFile = "maps/level_27_texture.png",
    playerStart = {x = 54, y = 30},
    platformXMin = 30,
    platformXMax = 60,
    bats = {
        {x = 48, y = 102},
        {x = 90, y = 144},
        {x = 72, y = 168},
        {x = 42, y = 168},
    },
    voidBats = {
        {x = 18, y = 102},
        {x = 30, y = 168},
        {x = 60, y = 168},
        {x = 66, y = 18},
        {x = 90, y = 54},
        {x = 78, y = 36},
    },
    mirrorLines = {
        {x = 84, y = 102, length = 18},
        {x = 6, y = 126, length = 24},
    },
    airWalls = {
        {x = 66, y = 30},
        {x = 24, y = 30},
    },
    safeZones = {
        {x = 54, y = 186},
        {x = 42, y = 186},
        {x = 30, y = 186},
        {x = 66, y = 186},
        {x = 78, y = 186},
    },
}

levels[28] = {
    stencilFile = "maps/level_28_stencil.png",
    textureFile = "maps/level_28_texture.png",
    playerStart = {x = 54, y = 162},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 18, y = 36},
        {x = 54, y = 36},
    },
    voidBats = {
        {x = 90, y = 156},
        {x = 54, y = 156},
    },
    jumpBats = {
        {x = 18, y = 156},
        {x = 90, y = 36},
    },
    mirrorLines = {
        {x = 6, y = 90, length = 30},
        {x = 72, y = 90, length = 32},
    },
    airWalls = {
        {x = 66, y = 162},
        {x = 42, y = 162},
    },
}

levels[29] = {
    stencilFile = "maps/level_29_stencil.png",
    textureFile = "maps/level_29_texture.png",
    playerStart = {x = 6, y = 114},
    platformXMin = 0,
    platformXMax = 12,
    bats = {
        {x = 18, y = 72, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
        {x = 66, y = 72, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
        {x = 42, y = 114, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = -1},
        {x = 90, y = 114, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = -1},
    },
    voidBats = {
        {x = 90, y = 174},
    },
    jumpBats = {
        {x = 66, y = 174},
        {x = 18, y = 174},
    },
    mirrorLines = {
        {x = 24, y = 96, length = 12},
        {x = 48, y = 96, length = 12},
        {x = 72, y = 96, length = 12},
    },
    airWalls = {
        {x = 18, y = 114},
    },
}

levels[30] = {
    stencilFile = "maps/level_30_stencil.png",
    textureFile = "maps/level_30_texture.png",
    playerStart = {x = 6, y = 114},
    platformXMin = 0,
    platformXMax = 12,
    bats = {
        {x = 12, y = 102},
    },
    voidBats = {
        {x = 42, y = 18},
    },
    jumpBats = {
        {x = 90, y = 18},
    },
    mirrorLines = {
        {x = 48, y = 96, length = 12},
        {x = 72, y = 96, length = 12},
        {x = 96, y = 96, length = 12},
        {x = 24, y = 96, length = 12},
    },
    airWalls = {
        {x = 18, y = 114},
    },
    safeZones = {
        {x = 108, y = 66},
        {x = 108, y = 78},
        {x = 108, y = 90},
        {x = 108, y = 102},
        {x = 108, y = 114},
        {x = 108, y = 126},
    },
}

levels[31] = {
    stencilFile = "maps/level_31_stencil.png",
    textureFile = "maps/level_31_texture.png",
    playerStart = {x = 54, y = 54},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 54, y = 174},
    },
    armorBats = {
        {x = 72, y = 174},
        {x = 36, y = 174},
    },
    airWalls = {
        {x = 66, y = 54},
        {x = 42, y = 54},
    },
}

levels[32] = {
    stencilFile = "maps/level_32_stencil.png",
    textureFile = "maps/level_32_texture.png",
    playerStart = {x = 54, y = 54},
    platformXMin = 48,
    platformXMax = 60,
    bats = {
        {x = 78, y = 126},
        {x = 30, y = 126},
        {x = 30, y = 90, moveDir = "HORIZONTAL", moveDist = 24, moveSpeed = 0.3, moveStartDir = 1},
    },
    voidBats = {
        {x = 78, y = 90, moveDir = "HORIZONTAL", moveDist = 24, moveSpeed = 0.3, moveStartDir = -1},
    },
    armorBats = {
        {x = 54, y = 150},
    },
    mirrorLines = {
        {x = 84, y = 108, length = 18},
        {x = 6, y = 108, length = 18},
    },
    airWalls = {
        {x = 66, y = 54},
        {x = 42, y = 54},
    },
}

levels[33] = {
    stencilFile = "maps/level_33_stencil.png",
    textureFile = "maps/level_33_texture.png",
    playerStart = {x = 42, y = 174},
    platformXMin = 36,
    platformXMax = 48,
    bats = {
        {x = 18, y = 18},
        {x = 66, y = 18},
    },
    voidBats = {
        {x = 90, y = 18},
    },
    jumpBats = {
        {x = 54, y = 162},
        {x = 42, y = 90},
    },
    armorBats = {
        {x = 54, y = 48},
        {x = 42, y = 18},
    },
    mirrorLines = {
        {x = 60, y = 90, length = 24},
    },
    airWalls = {
        {x = 54, y = 174},
        {x = 30, y = 174},
    },
}

levels[34] = {
    stencilFile = "maps/level_34_stencil.png",
    textureFile = "maps/level_34_texture.png",
    playerStart = {x = 78, y = 30},
    platformXMin = 72,
    platformXMax = 107,
    bats = {
        {x = 42, y = 138},
        {x = 66, y = 168},
        {x = 24, y = 54},
        {x = 48, y = 162},
        {x = 24, y = 108},
    },
    voidBats = {
        {x = 24, y = 132},
    },
    mirrorLines = {
        {x = 36, y = 96, length = 12},
        {x = 60, y = 96, length = 12},
        {x = 84, y = 96, length = 12},
    },
    airWalls = {
        {x = 66, y = 30},
    },
}

levels[35] = {
    stencilFile = "maps/level_35_stencil.png",
    textureFile = "maps/level_35_texture.png",
    playerStart = {x = 78, y = 30},
    platformXMin = 72,
    platformXMax = 96,
    bats = {
        {x = 24, y = 108},
        {x = 24, y = 54},
    },
    voidBats = {
        {x = 24, y = 132},
    },
    armorBats = {
        {x = 42, y = 138},
        {x = 48, y = 162},
        {x = 66, y = 168},
    },
    mirrorLines = {
        {x = 36, y = 96, length = 12},
        {x = 60, y = 96, length = 12},
        {x = 84, y = 96, length = 12},
    },
    airWalls = {
        {x = 66, y = 30},
        {x = 102, y = 30},
    },
}

levels[36] = {
    stencilFile = "maps/level_36_stencil.png",
    textureFile = "maps/level_36_texture.png",
    playerStart = {x = 78, y = 24},
    platformXMin = 72,
    platformXMax = 84,
    bats = {
    },
    jumpBats = {
        {x = 36, y = 168},
        {x = 72, y = 168},
    },
    armorBats = {
        {x = 72, y = 96, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = 1},
        {x = 36, y = 96, moveDir = "HORIZONTAL", moveDist = 36, moveSpeed = 0.3, moveStartDir = -1},
        {x = 54, y = 96, moveDir = "VERTICAL", moveDist = 48, moveSpeed = 0.3, moveStartDir = 1},
    },
    airWalls = {
        {x = 90, y = 24},
        {x = 66, y = 24},
    },
}

return levels
